version: '3.7'
services:
  iris:
    build:
      context: ./
      dockerfile: ./iris/Dockerfile
      args:
        PRODNAME: "iris"
        COMEDITION: "-community"
        VER: "latest-preview"
    container_name: iris
    restart: always
    ports:
      - 52773:52773
    environment:
      - TZ=JST-9
    volumes:
      - ../:/data
